@startuml
hide empty members
hide circle


abstract class Employee {
    -id
    -name
    -postal address
    -phone number
    -email
    -citizen card number
}

abstract class Center {
    -name
    -postal address
    -phone number
    -email
    -website address
    -open hour
    -close hour
    -maximum nº of vaccines per hour
}

class Nurse {
}

class Receptionist {
}


class HealthCare {
}

class CommunityMass {
}


class Dgsadmin {
    -id
    -name
    -email
}

class VaccineType {
    -code
    -disease
    -description
}

class Vaccine {
    -commercial name
    -brand
    -type
    -technology used
    -lot number
}

class Appointment {
    -date
    -time
    -status
}

class SNSUser {
    -name
    -date of birth
    -sex
    -postal address
    -phone number
    -email
    -nif
    -sns number
    -citizen card number
}


Employee <|-- Nurse
Employee <|-- Receptionist
Center <|-- HealthCare
Center <|-- CommunityMass

' Relações de Composição
VaccineType *-- "1..*" Vaccine : has >

' Relações de Associação
Dgsadmin "1" -- "0..*" Employee : manages >
Dgsadmin "1" -- "0..*" Center : manages >
Employee "0..*" -- "0..*" Center : works at >
Center "0..*" -- "1..*" VaccineType : provides >
SNSUser "1" -- "0..*" Appointment : schedules >
Appointment "0..*" -- "1" Center : scheduled at >
Appointment "0..*" -- "1" VaccineType : for >
Nurse "1" -- "0..*" Vaccine : administers >

@enduml