@startuml
'https://plantuml.com/sequence-diagram


autoactivate on
autonumber

actor "Administrator" as Admin
participant ":RegisterVaccineView" as View
participant ":RegisterVaccineController" as Ctrl
participant ":App" as AdminC
participant "Container:VaccineContainer" as VaccContainer
participant "Vac:Vaccine" as Vaccine


activate Admin

Admin -> View: Request to create a new vaccine
View -> Ctrl: createVaccine()
Ctrl -> AdminC: getVaccineContainer()
AdminC --> Ctrl: VaccContainer

Ctrl -> VaccContainer: create()
VaccContainer -> Vaccine**: create()
VaccContainer --> Ctrl: Vac
Ctrl --> View: ok
View --> Admin: Request details for vaccine

Admin -> View: types requested data
View -> Ctrl: set(commercial name,brand, technology used)
Ctrl -> Vaccine: setCN(commercial name)
Vaccine --> Ctrl: ok
Ctrl -> Vaccine: setB(brand)
Vaccine --> Ctrl: ok
Ctrl -> Vaccine: setTU(techonology used)
Vaccine --> Ctrl: ok

Ctrl -> VaccContainer: validate(Vac)
VaccContainer -> Vaccine: isValid()
Vaccine --> VaccContainer: ok
VaccContainer -> VaccContainer: checkduplicate(Vac)
VaccContainer --> VaccContainer: ok
VaccContainer --> Ctrl: ok
Ctrl --> View: ok
View-->Admin:Verifies provided data


Admin ->View:Confirms new vaccine registration
View->Ctrl: saveCreateVaccine()
Ctrl -> VaccContainer: save(Vac)
VaccContainer->VaccContainer: validate(Vac)
VaccContainer-->VaccContainer:ok
VaccContainer->VaccContainer: add(Vac)
VaccContainer-->VaccContainer:ok
VaccContainer-->Ctrl: ok
Ctrl-->View: ok
View-->Admin:Informs success of the operation






@enduml
