@startuml
'https://plantuml.com/class-diagram

hide circle
skinparam classAttributeIconSize 0

title Class Diagram - US11: Registar uma Vacina

class RegisterVaccineView {
    + displayRegistrationForm()
}


class RegisterVaccineController {
    + registerVaccine(data: VaccineDTO): VaccineDTO
}


class VaccineService {
    + registerVaccine(data: VaccineDTO): Vaccine
    + getAvailableTechnologies(): List<TechnologyType>
}


interface VaccineRepository {
    + save(vaccine: Vaccine): Vaccine
    + findByCommercialName(name: String): Vaccine
}

interface AdministrationProtocolRepository {
    + save(protocol: AdministrationProtocol): AdministrationProtocol
}



class Vaccine {

    - commercialName: String
    - brand: String
    --
    + getBrand(): String
    + getType(): VaccineType
}

class VaccineType {

    - code: String
    - disease: String
    - description: String
    --
    + getCode(): String
}

class AdministrationProtocol {

    - numberOfDoses: Integer
    - dosesIntervalInDays: Integer
    - minimumAge: Integer
    - maximumAge: Integer
}

class TechnologyType {

    - name: String
    - description: String
    --
    + getName(): String
}


RegisterVaccineView ..> RegisterVaccineController
RegisterVaccineController ..> VaccineService
VaccineService ..> VaccineRepository
VaccineService ..> AdministrationProtocolRepository



Vaccine "1..*" --> "1" VaccineType : "is of type"
Vaccine "1" --> "1" AdministrationProtocol : "has protocol"


Vaccine "1" --> "1" TechnologyType : "uses technology"


VaccineRepository "1" -- "0..*" Vaccine : "manages"
AdministrationProtocolRepository "1" -- "0..*" AdministrationProtocol : "manages"

@enduml