@startuml
'https://plantuml.com/class-diagram

hide circle
skinparam classAttributeIconSize 0
hide methods

title Modelo de Domínio - US11: Registar Vacina

class Vaccine {

    - commercialName: String
    - brand: String
    - technology used: String
}

class VaccineType {

    - code: String
    - disease: String
    - description: String
}

class AdministrationProtocol {

    - numberOfDoses: Integer
    - minimumAge: Integer
    - maximumAge: Integer
}


Vaccine "1" --> "1" AdministrationProtocol : "has protocol"

Vaccine "1..*" --> "1" VaccineType : "is of type"

@enduml