@startuml
'https://plantuml.com/sequence-diagram



autoactivate on
autonumber

actor "DGSadmin" as Admin
participant ":System" as System

activate Admin

Admin -> System: Requests to create a new vaccine
System --> Admin: Requests details for Vaccine

Admin -> System: Type requests data



Admin <-- System: Verifies provided data (e.g., confirms the selected Technology)

Admin -> System: Confirms new vaccine registration
System --> Admin: Informs success of the operation

deactivate Admin
@enduml