@startuml
'https://plantuml.com/sequence-diagram

hide circle
skinparam classAttributeIconSize 0

class RegisterVaccineView {
}

class RegisterVaccineController{
+createvaccine():void
+set(commercial name,brand, technology used): void
+ saveCreateVaccine():Result
}

class App{
+getVaccineContainer(): Vaccinecontainer
}

class VaccineContainer{
+create():Vaccine
+validate(Vac:Vaccine):boolean
+checkduplicate(Vac:Vaccine):boolean
+save(Vac:Vaccine):Result
}

class Vaccine{
-commercial name
-brand
-technology used
+setCN(commercial name)
+setB(brand)
+setTU(techonology used)
+isValid():boolean
}

App "1" -right-> "1" VaccineContainer: maintains
VaccineContainer "1" -down-> "0..*" Vaccine: records


RegisterVaccineView ..> RegisterVaccineController
RegisterVaccineController ..> App
RegisterVaccineController ..> VaccineContainer
RegisterVaccineController ..> Vaccine



@enduml