@startuml
'https://plantuml.com/sequence-diagram

title Sequence Diagram - US14: Register Employee

autoactivate on
autonumber

actor "Administrator" as Admin
participant ":RegisterEmployeeView" as view
participant ":RegisterEmployeeController" as Ctrl
participant ":EmployeeService" as Srv
participant ":EmployeeRepository" as Repo

activate Admin
Admin -> view : Submete dados do novo empregado
view -> Ctrl : registerEmployee(data)

Ctrl -> Srv : registerEmployee(data)
' AC14-4: Verifica unicidade
Srv -> Repo : findByEmail(email)
Repo --> Srv : (null)
Srv -> Repo : findByPhoneNumber(phone)
Repo --> Srv : (null)

' Cria e guarda a nova entidade
Srv -> Repo : save(newEmployee)
Repo --> Srv : savedEmployee

Srv --> Ctrl : employeeDTO
Ctrl --> view : operationSuccess()
view --> Admin : Exibe mensagem de sucesso

@enduml