@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0
hide methods

title Domain Model Excerpt - US14

class Employee {
    ' AC14-2: Atributos obrigatórios
    -name: String
    -phoneNumber: String
    -emailAddress: String
    ' AC14-3: Formato PT
    -citizenCardNumber: String
}

class Role {
    ' AC14-1: Função/role
    -description: String
}

' AC14-1: Cada empregado tem uma única função
Employee "1" --> "1" Role : "is assigned to"

@enduml