@startuml

class worker{
-Id
-Name
-Postal adress
-Phone number
-Email
}

class Nurse{
}

class Receptionist{
}

class Appointment{
-sns number
-date
}

class Dgsadmin{
-id
-name
-email

}
class Center {
-name
-postal address
-phone number
-email
-website address
-open hour
-close hour
-maximum nº of vaccines per hour
}

class CommunityMass{

}

class VacineType{
-code
-disease
-commercial name
-brand
-type
-techonoly used
}

class SNSUser{
-name
-date of birth
-sex
-postal address
-phone number
-email
-nif
-sns number
-citizen card number
}
SNSUser"0...*" -left-- "1" Center:  registered in >
Center "1" --- "0..*" HealthCare:  provides >
Center "1" --- "0..*" CommunityMass:  provides >
worker "1" --- "0..*" Nurse: Can be >
worker "1" --- "0..*" Receptionist: Can be >
User "1" --- "0..*" SNSUser: Have >
worker "1" --- "0..*" Center: Have <
SNSUser "1" --- "0..*" Appointment: schedule >
User "1" -left-- "0..*" VacineType: Select >
Dgsadmin "1" --- "0..*" Center: Managing >
Dgsadmin "1" --- "0..*" worker: Managing >


@enduml
